//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Inconsistencies = new HashSet<Inconsistency>();
            this.Proveedors = new HashSet<Proveedor>();
        }
    
        public string ClientId { get; set; }
        public string EmpresarialGroup { get; set; }
        public string RegistryTributario { get; set; }
        public string FiscalTypeId { get; set; }
        public string Address { get; set; }
        public string WebPage { get; set; }
        public string BussinesActivity { get; set; }
        public string ProductLineId { get; set; }
        public string Vision { get; set; }
        public string Mision { get; set; }
        public string Valores { get; set; }
        public string CountryId { get; set; }
        public string Phone { get; set; }
        public string Industry { get; set; }
        public string IndustryType { get; set; }
        public string RSE { get; set; }
        public string Marcas { get; set; }
        public string MarketId { get; set; }
        public string BillingCountryId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual Client Client2 { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual User User { get; set; }
        public virtual FiscalType FiscalType { get; set; }
        public virtual IndustryType IndustryType1 { get; set; }
        public virtual Country Country2 { get; set; }
        public virtual User User1 { get; set; }
        public virtual ProductLine ProductLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inconsistency> Inconsistencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proveedor> Proveedors { get; set; }
    }
}
