//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inconsistency
    {
        public string InconsistencyId { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string ClienteId { get; set; }
        public string HojaRuta { get; set; }
        public string ProveedorId { get; set; }
        public string DocumentId { get; set; }
        public string DocumentNumber { get; set; }
        public string CategoryId { get; set; }
        public string Comentario { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Client Client { get; set; }
        public virtual Document Document { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
