//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExpedientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inconsistencia
    {
        public int InconsistenciaId { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public int Cliente { get; set; }
        public string HojaRuta { get; set; }
        public int Proveedor { get; set; }
        public int Documento { get; set; }
        public string NumeroDocumento { get; set; }
        public int Categoria { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual Categoria Categoria1 { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual Documento Documento1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Proveedor Proveedor1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
