//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExpedientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Inconsistencias = new HashSet<Inconsistencia>();
        }
    
        public int ProveedorId { get; set; }
        public string Proveedor1 { get; set; }
        public string IdentificadorFiscal { get; set; }
        public int TipoIdentificador { get; set; }
        public int GrupoPersona { get; set; }
        public int Cliente { get; set; }
        public int Pais { get; set; }
        public int PaisOperacion { get; set; }
        public int Segmento { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual GrupoPersona GrupoPersona1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inconsistencia> Inconsistencias { get; set; }
        public virtual Pai Pai { get; set; }
        public virtual Pai Pai1 { get; set; }
        public virtual Segmento Segmento1 { get; set; }
        public virtual TipoFiscal TipoFiscal { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
