//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExpedientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCredito
    {
        public int CreditoId { get; set; }
        public int Cliente { get; set; }
        public string TramitesMensualesEsperados { get; set; }
        public string ProyeccionCM1Mensual { get; set; }
        public string ProyeccionVolumenMensual { get; set; }
        public Nullable<decimal> MontoSolicitado { get; set; }
        public Nullable<int> TiempoCredito { get; set; }
        public int Modeda { get; set; }
        public string Division { get; set; }
        public int TipoPago { get; set; }
        public string FinanciamientoImpuestos { get; set; }
        public decimal TiempoCreditoImpuesto { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual TipoPago TipoPago1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
